# Generated by Django 5.1.7 on 2025-04-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uenowebsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
