# Generated by Django 5.1.7 on 2025-04-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uenowebsite', '0002_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Full Name')),
                ('company_name', models.CharField(max_length=128, verbose_name='Company Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('enquiry', models.TextField(blank=True, null=True, verbose_name='Enquiry Details')),
                ('product_choice', models.CharField(choices=[('machinery', 'Machinery'), ('steel', 'Steel'), ('tools', 'Tools'), ('other', 'Other')], max_length=20, verbose_name='Product Interested In')),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
