# Generated by Django 5.1.7 on 2025-04-13 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uenowebsite', '0003_enquiry_alter_category_options_alter_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('overview', models.TextField()),
                ('specifications', models.TextField()),
                ('countries_sold', models.CharField(max_length=255)),
                ('is_new', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('catalog_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
