# Generated by Django 5.1.7 on 2025-04-18 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uenowebsite', '0004_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='buildings/')),
                ('series', models.CharField(max_length=255)),
            ],
        ),
    ]
