# Generated by Django 5.1.7 on 2025-05-26 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uenowebsite', '0005_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='building',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='building',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='UenoBuildings/'),
        ),
        migrations.AlterField(
            model_name='building',
            name='series',
            field=models.CharField(max_length=100),
        ),
    ]
