from django.core.management.base import BaseCommand
from uenowebsite.models import Product

class Command(BaseCommand):
    help = 'Load initial product data into the database'

    def handle(self, *args, **kwargs):
        products = [
            {
                "name": "OTC-Daihen Robots",
                "category": "Robots",
                "description": "Welding machines and robots (MIG/MAG/TIG/PLASMA) from Japan.",
                "overview": "Advanced Japanese welding automation for industrial settings.",
                "specifications": "Power: 6kW, Axis: 6-axis, Interface: PLC-compatible",
                "countries_sold": "Japan, India, Vietnam",
                "is_new": True,
            },

            {
                "name": "Fencing & Hanger Making Machines",
                "category": "Industrial Equipment",
                "description": "SHIN-EI TEC's specialized fencing and hanger machines from Japan.",
                "overview": "Robust build, high-speed, low-maintenance units.",
                "specifications": "Voltage: 440V, Phase: 3, Speed: 300 units/hr",
                "countries_sold": "India, Indonesia, Egypt",
                "is_new": True,
            },

            {
                "name": "Pipe Threading & Grooving Machines",
                "category": "Industrial Equipment",
                "description": "REX Japan machines for threading and grooving pipes.",
                "overview": "Industrial threading solutions with high precision.",
                "specifications": "Capacity: 1/2\"–4\", Motor: 1100W",
                "countries_sold": "India, Vietnam, Nigeria",
                "is_new": True,
            },
            {
                "name": "Welding Electrodes",
                "category": "Industrial Equipment",
                "description": "Top-grade electrodes by NICHIA and NIKKO, Malaysia.",
                "overview": "High-performance industrial electrodes with smooth arc.",
                "specifications": "Type: E6013, Size: 2.5mm, Origin: Malaysia",
                "countries_sold": "India, Nepal, Indonesia",
                "is_new": True,
            },
            {
                "name": "Hand Trucks & Trolleys",
                "category": "Industrial Equipment",
                "description": "Transport tools by PRESTAR Japan — trolleys, castors, etc.",
                "overview": "Heavy-duty mobility solutions for warehouses and logistics.",
                "specifications": "Load: 150kg, Wheels: Pneumatic rubber, Material: Steel",
                "countries_sold": "India, UAE, Kenya",
                "is_new": True,
            },
            {
                "name": "Hot Rolled Coils (HRC)",
                "category": "Steel Products",
                "description": "HRC used in construction and auto industries from Japan, Korea, Taiwan, China.",
                "overview": "High-strength structural-grade hot rolled coils.",
                "specifications": "Thickness: 1.5-10mm, Width: 1000-1500mm",
                "countries_sold": "India, Bangladesh, UAE",
                "is_new": True,
            },
            {
                "name": "Stainless Steel Bars & Sheets",
                "category": "Steel Products",
                "description": "Stainless steel rods, bars, and sheets from Japan, Korea, and Taiwan.",
                "overview": "Polished, corrosion-resistant steel for industrial fabrication.",
                "specifications": "Grades: 304/316, Finish: Mirror/Matte",
                "countries_sold": "India, Oman, Singapore",
                "is_new": True,
            },
            {
                "name": "Pre-painted GI Sheets & Coils",
                "category": "Steel Products",
                "description": "Color-coated galvanized coils for structural and aesthetic use.",
                "overview": "Durable, weather-resistant, pre-painted steel options.",
                "specifications": "Thickness: 0.3–0.7mm, Colors: RAL range",
                "countries_sold": "India, Africa, Middle East",
                "is_new": True,
            },
            {
                "name": "Expanded Metal Machine",
                "category": "Industrial Machinery",
                "description": "High-speed expanded metal machine from Korea and Taiwan.",
                "overview": "Heavy-duty mesh production equipment.",
                "specifications": "Material: Carbon steel, Output: 200m/hr",
                "countries_sold": "India, Bangladesh, Vietnam",
                "is_new": True,
            },
            {
                "name": "Cold Roll-forming Line",
                "category": "Industrial Machinery",
                "description": "Roll-forming machines for structural steel applications.",
                "overview": "Versatile forming lines from Korea & Taiwan.",
                "specifications": "Material Width: up to 1250mm, Speed: 15m/min",
                "countries_sold": "India, UAE, Kenya",
                "is_new": True,
            },

            {
                "name": "Pre-painted Aluminum Coils",
                "category": "Steel Products",
                "description": "Color-coated aluminum coils for industrial and architectural use.",
                "overview": "Weather-resistant, lightweight, pre-painted aluminum solutions.",
                "specifications": "Thickness: 0.3–0.7mm, Coating: PE/PVDF",
                "countries_sold": "India, Middle East, Africa",
                "is_new": True,
            },
            {
                "name": "Galvanized Coils",
                "category": "Steel Products",
                "description": "Zinc-coated steel coils used in construction and fabrication.",
                "overview": "Corrosion-resistant galvanized coils for structural applications.",
                "specifications": "Thickness: 0.2–2.5mm, Width: 600–1250mm",
                "countries_sold": "India, Bangladesh, UAE",
                "is_new": True,
            },
            {
                "name": "H-Beams & IPEAA",
                "category": "Steel Products",
                "description": "Structural steel H-beams and IPEAA beams for construction frameworks.",
                "overview": "High-strength support members in a variety of sizes and grades.",
                "specifications": "Standard: JIS/EN, Length: 6m–12m",
                "countries_sold": "India, Indonesia, Qatar",
                "is_new": True,
            },
            {
                "name": "Carbon Steel Plates",
                "category": "Steel Products",
                "description": "Heavy-duty carbon steel plates for industrial use.",
                "overview": "High-tensile strength plates used in fabrication and shipbuilding.",
                "specifications": "Grade: ASTM A36, Thickness: 6mm–100mm",
                "countries_sold": "India, UAE, Egypt",
                "is_new": True,
            },
            {
                "name": "Galvanized Sheets, Angles",
                "category": "Steel Products",
                "description": "Zinc-coated sheets and L-angle bars for structural support.",
                "overview": "Multipurpose galvanized profiles for infrastructure projects.",
                "specifications": "Angle Size: 25x25mm–100x100mm, Sheet Gauge: 18–24",
                "countries_sold": "India, Nepal, Sri Lanka",
                "is_new": True,
            },
            {
                "name": "Wire Rod",
                "category": "Steel Products",
                "description": "Round steel rod in coils used for wire drawing and rebar.",
                "overview": "Versatile steel wire rod for manufacturing and construction.",
                "specifications": "Diameter: 5.5mm–14mm, Grade: SAE 1006/1008",
                "countries_sold": "India, Kenya, Vietnam",
                "is_new": True,
            },
            {
                "name": "U-Channel",
                "category": "Steel Products",
                "description": "Steel U-channels used in fabrication and support structures.",
                "overview": "Durable, galvanized or black-finish U-channel beams.",
                "specifications": "Size: 75x40mm–300x90mm, Length: 6–12m",
                "countries_sold": "India, Bangladesh, UAE",
                "is_new": True,
            },
            {
                "name": "UPE & UPN",
                "category": "Steel Products",
                "description": "UPE and UPN European standard steel channels.",
                "overview": "Precision-rolled channels for industrial and commercial frameworks.",
                "specifications": "UPE: 80–400, UPN: 50–300",
                "countries_sold": "India, Turkey, Saudi Arabia",
                "is_new": True,
            },
            {
                "name": "Hot Rolled Plates",
                "category": "Steel Products",
                "description": "Uncoated hot rolled steel plates used in fabrication.",
                "overview": "Industrial-grade plates for welding, cutting, and forming.",
                "specifications": "Thickness: 6–100mm, Width: up to 2500mm",
                "countries_sold": "India, Africa, Southeast Asia",
                "is_new": True,
            },
            {
                "name": "Zinc Plated Sheets",
                "category": "Steel Products",
                "description": "Steel sheets with zinc coating for rust resistance.",
                "overview": "Cost-effective anti-corrosive flat steel sheets.",
                "specifications": "Gauge: 22–28, Width: 600–1220mm",
                "countries_sold": "India, Sri Lanka, Myanmar",
                "is_new": True,
            },
            {
                "name": "Round Bar",
                "category": "Steel Products",
                "description": "Solid cylindrical bars used in machining and construction.",
                "overview": "Hot rolled or bright finished steel round bars.",
                "specifications": "Diameter: 8mm–100mm, Grade: EN8/EN9",
                "countries_sold": "India, UAE, Malaysia",
                "is_new": True,
            },
            {
                "name": "Chequered Coil",
                "category": "Steel Products",
                "description": "Textured surface coils used in flooring and walkways.",
                "overview": "Anti-slip patterned steel coils for safety applications.",
                "specifications": "Thickness: 2–6mm, Pattern: Tear/diamond",
                "countries_sold": "India, Vietnam, Bahrain",
                "is_new": True,
            },
            {
                "name": "Tube & Pipe, Rebar",
                "category": "Steel Products",
                "description": "Steel pipes, tubes, and reinforcement bars for structural use.",
                "overview": "Full range of MS pipes and rebars for infrastructure and plumbing.",
                "specifications": "Rebar: TMT Fe500D, Pipe Size: 0.5–8 inch",
                "countries_sold": "India, Nigeria, UAE",
                "is_new": True,
            },
            {
                "name": "MS Sheets / Plates / Tubes",
                "category": "Steel Products",
                "description": "Mild steel flat and hollow sections used in fabrication.",
                "overview": "Versatile MS products for various manufacturing needs.",
                "specifications": "Sheet Gauge: 16–22, Plate Thickness: 6–50mm, Tube: Square/Rectangular",
                "countries_sold": "India, Nepal, Africa",
                "is_new": True,
            },

            {
                "name": "SKC Taps and Dies",
                "category": "Industrial Equipment",
                "description": "Precision threading tools from SKC Japan, including taps and dies.",
                "overview": "High-quality threading solutions for mechanical and fabrication industries.",
                "specifications": "Sizes: M3–M30, Material: HSS, Standards: JIS/DIN",
                "countries_sold": "India, UAE, Vietnam",
                "is_new": True,
                },
                
                {
                    "name": "Tamper Rammers and Vibratory Rollers",
                    "category": "Industrial Equipment",
                    "description": "Compaction machinery including tamper rammers and single/double drum vibratory rollers.",
                    "overview": "Heavy-duty ground compactors for roadwork and construction.",
                    "specifications": "Engine: Diesel/Petrol, Force: 10–30 kN, Drum Width: 600–1200mm",
                    "countries_sold": "India, Bangladesh, Kenya",
                    "is_new": True,
                    },
                    
                    {
                        "name": "Measuring Equipment (Multimeter, Clamp Meter, Electric Tools)",
                        "category": "Industrial Equipment",
                        "description": "Electrical measuring instruments and testing tools for industrial applications.",
                        "overview": "Accurate and reliable meters for voltage, current, resistance, and diagnostics.",
                        "specifications": "Multimeter: Auto-ranging, Clamp Meter: 600A AC/DC, Brands: Sanwa, Kyoritsu",
                        "countries_sold": "India, Philippines, Nigeria",
                        "is_new": True,
                        },
                        {
                            "name": "Bullox Hammers",
                            "category": "Industrial Equipment",
                            "description": "Heavy-duty forged steel hammers for industrial striking applications.",
                            "overview": "Durable Bullox hammers ideal for construction, rail, and mining sectors.",
                            "specifications": "Weight: 1kg–10kg, Handle: Fiberglass/Wood, Type: Sledge/Club",
                            "countries_sold": "India, Africa, UAE",
                            "is_new": True,
                            },
        ]

        for p in products:
            product, created = Product.objects.get_or_create(name=p["name"], defaults=p)
            if created:
                self.stdout.write(self.style.SUCCESS(f"Created product: {product.name}"))
            else:
                self.stdout.write(self.style.WARNING(f"Product already exists: {product.name}"))
